"""changing cache table

Revision ID: a84478ec5e31
Revises: 
Create Date: 2022-11-29 03:25:40.096576

"""
from alembic import op
import sqlalchemy as sa
from models import session, Page_number

# revision identifiers, used by Alembic.
revision = 'a84478ec5e31'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Buffer_buttons',
    sa.Column('button', sa.String(), nullable=False),
    sa.Column('script_part', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('button')
    )
    op.create_table('Buffer_values',
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('script_part', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('value')
    )
    op.create_table('Cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Group_ids',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('Page_number',
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('page_number')
    )
    op.create_table('Users_ids',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('Words',
    sa.Column('word', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('word')
    )
    # ### end Alembic commands ###
    page = session.query(Page_number).first()
    if not page:
        session.add(Page_number(page_number=0))
        session.commit()
        print('Добавлено значение страницы')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Words')
    op.drop_table('Users_ids')
    op.drop_table('Page_number')
    op.drop_table('Group_ids')
    op.drop_table('Cache')
    op.drop_table('Buffer_values')
    op.drop_table('Buffer_buttons')
    # ### end Alembic commands ###
